import { ProjectsSectionType } from '@/lib/types/sections';
import { getId } from '@/lib/utils/helper';

// https://icon-sets.iconify.design/vscode-icons/

export const projectsSection: ProjectsSectionType = {
  title: 'other projects',
  projects: [
    {
      id: getId(),
      name: 'Chicken Road Game',
      url: 'https://drive.google.com/file/d/1rEoe6RwU_WINLsHTNAuiYmpxZlYzJcuj/view?usp=sharing',
      repo: 'https://github.com/Mahmud0808/ChickenRoad',
      img: 'https://i.postimg.cc/xTS0K9NM/chicken-road-banner.png',
      year: 2025,
      projectSkills: [
        { name: 'Kotlin', icon: 'vscode-icons:file-type-kotlin' },
      ],
    },
    {
      id: getId(),
      name: 'PixelLauncher Enhanced',
      url: 'https://github.com/Mahmud0808/PixelLauncherEnhanced',
      repo: 'https://github.com/Mahmud0808/PixelLauncherEnhanced',
      img: 'https://i.postimg.cc/cHmVwGpM/pixellauncher-enhanced-banner.png',
      year: 2025,
      projectSkills: [
        { name: 'Kotlin', icon: 'vscode-icons:file-type-kotlin' },
        { name: 'XML', icon: 'vscode-icons:file-type-xml' },
      ],
    },
    {
      id: getId(),
      name: 'Truck Orbit',
      url: 'https://github.com/Mahmud0808/TruckOrbit',
      repo: 'https://github.com/Mahmud0808/TruckOrbit',
      img: 'https://i.postimg.cc/MHr8wWPr/Truck-Orbit.png',
      year: 2025,
      projectSkills: [
        { name: 'Kotlin', icon: 'vscode-icons:file-type-kotlin' },
        { name: 'Firebase', icon: 'vscode-icons:file-type-firebase' },
        { name: 'Maps API', icon: 'logos:google-maps' },
      ],
    },
    {
      id: getId(),
      name: 'Exam Timer',
      url: 'https://quiktimer.vercel.app',
      repo: 'https://github.com/Mahmud0808/ExamTimer',
      img: 'https://i.postimg.cc/1Xtd7rQS/Exam-Timer.png',
      year: 2024,
      projectSkills: [
        { name: 'Next.js', icon: 'file-icons:nextjs' },
        { name: 'Tailwind CSS', icon: 'vscode-icons:file-type-tailwind' },
      ],
    },
    {
      id: getId(),
      name: 'Breakdown Assistance',
      url: 'https://github.com/Mahmud0808/BreakdownAssistance',
      repo: 'https://github.com/Mahmud0808/BreakdownAssistance',
      img: 'https://i.postimg.cc/3Jsq0QGT/Breakdown-Assistance.png',
      year: 2024,
      projectSkills: [
        { name: 'Java', icon: 'hugeicons:java' },
        { name: 'Firebase', icon: 'vscode-icons:file-type-firebase' },
        { name: 'Maps API', icon: 'logos:google-maps' },
      ],
    },
    {
      id: getId(),
      name: 'NexuTalk',
      url: 'https://nexutalk.vercel.app/',
      repo: 'https://github.com/Mahmud0808/NexuTalk',
      img: 'https://i.postimg.cc/FhzMbpVC/Screen-Shot-Tool-20240804191942.png',
      year: 2024,
      projectSkills: [
        { name: 'Next.js', icon: 'file-icons:nextjs' },
        { name: 'NextAuth.js', icon: 'noto-v1:shield' },
        { name: 'MongoDB', icon: 'vscode-icons:file-type-mongo' },
        { name: 'Tailwind CSS', icon: 'vscode-icons:file-type-tailwind' },
        { name: 'Prisma', icon: 'simple-icons:prisma' },
        { name: 'Pusher', icon: 'simple-icons:pusher' },
      ],
    },
    {
      id: getId(),
      name: 'MernAuth',
      url: 'https://mernauth-mwjp.onrender.com/',
      repo: 'https://github.com/Mahmud0808/MernAuth',
      img: 'https://i.postimg.cc/L9gTVFCs/MernAuth.png',
      year: 2024,
      projectSkills: [
        { name: 'MongoDB', icon: 'vscode-icons:file-type-mongo' },
        { name: 'Express', icon: 'skill-icons:expressjs-light' },
        { name: 'React', icon: 'vscode-icons:file-type-reactjs' },
        { name: 'Node.js', icon: 'vscode-icons:file-type-node' },
        { name: 'Tailwind CSS', icon: 'vscode-icons:file-type-tailwind' },
        { name: 'Firebase', icon: 'vscode-icons:file-type-firebase' },
      ],
    },
    {
      id: getId(),
      name: 'Melodify',
      url: 'https://github.com/Mahmud0808/Melodify',
      repo: 'https://github.com/Mahmud0808/Melodify',
      img: 'https://i.postimg.cc/WbYQ7f55/Melodify.png',
      year: 2024,
      projectSkills: [
        { name: 'Flutter', icon: 'vscode-icons:file-type-flutter' },
        { name: 'Dart', icon: 'vscode-icons:file-type-dartlang' },
        { name: 'Music Player', icon: 'emojione-v1:music-descend' },
      ],
    },
    {
      id: getId(),
      name: 'ResumeAI',
      url: 'https://resume-ai-app.vercel.app/',
      repo: 'https://github.com/Mahmud0808/ResumeAI',
      img: 'https://i.postimg.cc/DnJHZ229/Resume-AI.png',
      year: 2024,
      projectSkills: [
        { name: 'Next.js', icon: 'file-icons:nextjs' },
        { name: 'Tailwind CSS', icon: 'vscode-icons:file-type-tailwind' },
        { name: 'MongoDB', icon: 'vscode-icons:file-type-mongo' },
        { name: 'Clerk', icon: 'simple-icons:clerk' },
        { name: 'Gemini API', icon: 'ri:gemini-fill' },
      ],
    },
    {
      id: getId(),
      name: 'Quanta Bank',
      url: 'https://github.com/Mahmud0808/QuantaBank',
      repo: 'https://github.com/Mahmud0808/QuantaBank',
      img: 'https://i.postimg.cc/66gtfQJP/quanta-bank.png',
      year: 2024,
      projectSkills: [
        { name: 'Next.js', icon: 'file-icons:nextjs' },
        { name: 'Tailwind CSS', icon: 'vscode-icons:file-type-tailwind' },
        { name: 'Clerk', icon: 'simple-icons:clerk' },
        { name: 'Appwrite', icon: 'logos:appwrite-icon' },
        { name: 'Sentry', icon: 'vscode-icons:file-type-sentry' },
      ],
    },
    {
      id: getId(),
      name: 'Quirklr',
      url: 'https://quirklrapp.vercel.app/',
      repo: 'https://github.com/Mahmud0808/Quirklr',
      img: 'https://i.postimg.cc/hSL5JvrB/quirklr.png',
      year: 2024,
      projectSkills: [
        { name: 'Next.js', icon: 'file-icons:nextjs' },
        { name: 'Tailwind CSS', icon: 'vscode-icons:file-type-tailwind' },
        { name: 'MongoDB', icon: 'vscode-icons:file-type-mongo' },
        { name: 'Clerk', icon: 'simple-icons:clerk' },
      ],
    },
    {
      id: getId(),
      name: 'Nexara Cart',
      url: 'https://github.com/Mahmud0808/NexaraCart',
      repo: 'https://github.com/Mahmud0808/NexaraCart',
      img: 'https://i.postimg.cc/0ksn4Wjx/Nexara-Cart.png',
      year: 2024,
      projectSkills: [
        { name: 'Flutter', icon: 'vscode-icons:file-type-flutter' },
        { name: 'Dart', icon: 'vscode-icons:file-type-dartlang' },
        { name: 'Node.js', icon: 'vscode-icons:file-type-node' },
      ],
    },
    {
      id: getId(),
      name: 'Lumi Weather',
      url: 'https://github.com/Mahmud0808/LumiWeather',
      repo: 'https://github.com/Mahmud0808/LumiWeather',
      img: 'https://i.postimg.cc/B4GHsLBZ/Lumi-Weather.png',
      year: 2024,
      projectSkills: [
        { name: 'Flutter', icon: 'vscode-icons:file-type-flutter' },
        { name: 'Dart', icon: 'vscode-icons:file-type-dartlang' },
      ],
    },
    {
      id: getId(),
      name: 'TG Join Bot',
      url: 'https://github.com/Mahmud0808/TelegramJoinRequestVerifier',
      repo: 'https://github.com/Mahmud0808/TelegramJoinRequestVerifier',
      img: 'https://i.postimg.cc/hgntt96Y/TGJoin-Bot.png',
      year: 2024,
      projectSkills: [
        { name: 'Kotlin', icon: 'vscode-icons:file-type-kotlin' },
        { name: 'Telegram', icon: 'logos:telegram' },
        { name: 'Bot', icon: 'bxs:bot' },
      ],
    },
    {
      id: getId(),
      name: 'UniRide',
      url: 'https://github.com/Mahmud0808/UniRide',
      repo: 'https://github.com/Mahmud0808/UniRide',
      img: 'https://i.postimg.cc/4GFBY02y/uniride.png',
      year: 2024,
      projectSkills: [
        { name: 'Kotlin', icon: 'vscode-icons:file-type-kotlin' },
        { name: 'Firebase', icon: 'vscode-icons:file-type-firebase' },
        { name: 'Maps API', icon: 'logos:google-maps' },
        { name: 'Gemini API', icon: 'ri:gemini-fill' },
      ],
    },
    {
      id: getId(),
      name: 'Conversa',
      url: 'https://github.com/Mahmud0808/Conversa',
      repo: 'https://github.com/Mahmud0808/Conversa',
      img: 'https://i.postimg.cc/VsgKtc87/conversa.png',
      year: 2024,
      projectSkills: [
        { name: 'Kotlin', icon: 'vscode-icons:file-type-kotlin' },
        { name: 'Gemini API', icon: 'ri:gemini-fill' },
      ],
    },
    {
      id: getId(),
      name: 'Rushly',
      url: 'https://github.com/Mahmud0808/Rushly',
      repo: 'https://github.com/Mahmud0808/Rushly',
      img: 'https://i.postimg.cc/yN3mpw2z/rushly.webp',
      year: 2024,
      projectSkills: [
        { name: 'Kotlin', icon: 'vscode-icons:file-type-kotlin' },
        { name: 'Firebase', icon: 'vscode-icons:file-type-firebase' },
      ],
    },
    {
      id: getId(),
      name: 'ThunderDex',
      url: 'https://play.google.com/store/apps/details?id=io.hifii.wiki',
      repo: 'https://github.com/Mahmud0808/WarThunderWiki',
      img: 'https://i.postimg.cc/VvV21ysW-/opengraph-wt.jpg',
      year: 2024,
      projectSkills: [
        { name: 'Java', icon: 'hugeicons:java' },
        { name: 'HTML', icon: 'vscode-icons:file-type-html' },
        { name: 'War Thunder', icon: 'healthicons:war' },
      ],
    },
    {
      id: getId(),
      name: 'RemiLab',
      url: 'https://github.com/Mahmud0808/RemiLab',
      repo: 'https://github.com/Mahmud0808/RemiLab',
      img: 'https://i.postimg.cc/Fs9sP3wr/remilab.png',
      year: 2024,
      projectSkills: [
        { name: 'Java', icon: 'hugeicons:java' },
        { name: 'Shell Script', icon: 'vscode-icons:file-type-shell' },
        {
          name: 'Preference Manager',
          icon: 'material-symbols:room-preferences-rounded',
        },
      ],
    },
    {
      id: getId(),
      name: 'Sonix Spectrum',
      url: 'https://github.com/Mahmud0808/Sonix-Spectrum',
      repo: 'https://github.com/Mahmud0808/Sonix-Spectrum',
      img: 'https://i.postimg.cc/cCs23Vcf/sonixspectrum.jpg',
      year: 2024,
      projectSkills: [
        { name: 'Java', icon: 'hugeicons:java' },
        { name: 'Shell Script', icon: 'vscode-icons:file-type-shell' },
        { name: 'Kernel Manager', icon: 'ph:cpu-bold' },
      ],
    },
    {
      id: getId(),
      name: 'SheGuard',
      url: 'https://github.com/Mahmud0808/SheGuard',
      repo: 'https://github.com/Mahmud0808/SheGuard',
      img: 'https://i.postimg.cc/rVfKvhCd/sheguard.png',
      year: 2023,
      projectSkills: [
        { name: 'Java', icon: 'hugeicons:java' },
        { name: 'Firebase', icon: 'vscode-icons:file-type-firebase' },
      ],
    },
    {
      id: getId(),
      name: 'MusicPlayer',
      url: 'https://mahmud0808.github.io/MusicPlayer',
      repo: 'https://github.com/Mahmud0808/MusicPlayer',
      img: 'https://i.postimg.cc/D2TNDhgz/musicplayer.png',
      year: 2023,
      projectSkills: [
        { name: 'HTML', icon: 'vscode-icons:file-type-html' },
        { name: 'CSS', icon: 'vscode-icons:file-type-css' },
        { name: 'JavaScript', icon: 'vscode-icons:file-type-js' },
        { name: 'Music Player', icon: 'emojione-v1:music-descend' },
      ],
    },
    {
      id: getId(),
      name: 'QuizMania',
      url: 'https://mahmud0808.github.io/QuizMania',
      repo: 'https://github.com/Mahmud0808/QuizMania',
      img: 'https://i.postimg.cc/R404s70Y/quizmania.png',
      year: 2023,
      projectSkills: [
        { name: 'HTML', icon: 'vscode-icons:file-type-html' },
        { name: 'CSS', icon: 'vscode-icons:file-type-css' },
        { name: 'JavaScript', icon: 'vscode-icons:file-type-js' },
      ],
    },
    {
      id: getId(),
      name: 'FRAS',
      url: 'https://github.com/Mahmud0808/FRAS',
      repo: 'https://github.com/Mahmud0808/FRAS',
      img: 'https://i.postimg.cc/59phw2QG/fras.jpg',
      year: 2022,
      projectSkills: [
        { name: 'Python', icon: 'vscode-icons:file-type-python' },
        { name: 'Flask', icon: 'simple-icons:flask' },
        { name: 'Image Processing', icon: 'ic:baseline-face' },
      ],
    },
    {
      id: getId(),
      name: 'Gadgets',
      url: 'https://mahmud0808.github.io/Gadgets',
      repo: 'https://github.com/Mahmud0808/Gadgets',
      img: 'https://i.postimg.cc/MqWPSt2W/gadgets.png',
      year: 2022,
      projectSkills: [
        { name: 'HTML', icon: 'vscode-icons:file-type-html' },
        { name: 'CSS', icon: 'vscode-icons:file-type-css' },
      ],
    },
    {
      id: getId(),
      name: 'Another Theme',
      url: 'https://www.pling.com/p/1732643',
      repo: 'https://github.com/Mahmud0808/AnotherTheme',
      img: 'https://i.postimg.cc/FN3T3qyg/heroimage.png',
      year: 2022,
      projectSkills: [
        { name: 'Kotlin', icon: 'vscode-icons:file-type-kotlin' },
        { name: 'XML', icon: 'vscode-icons:file-type-xml' },
      ],
    },
    {
      id: getId(),
      name: 'Pink Bean (Monet)',
      url: 'https://www.pling.com/p/1732643',
      repo: 'https://github.com/Mahmud0808/PinkBeanMonet',
      img: 'https://i.postimg.cc/xngVLcyP/heroimage.png',
      year: 2022,
      projectSkills: [
        { name: 'Kotlin', icon: 'vscode-icons:file-type-kotlin' },
        { name: 'XML', icon: 'vscode-icons:file-type-xml' },
      ],
    },
    {
      id: getId(),
      name: 'Pink Bean',
      url: 'https://www.pling.com/p/1732643',
      repo: 'https://github.com/Mahmud0808/PinkBean',
      img: 'https://i.postimg.cc/v8McjcKm/heroimage.png',
      year: 2022,
      projectSkills: [
        { name: 'Kotlin', icon: 'vscode-icons:file-type-kotlin' },
        { name: 'XML', icon: 'vscode-icons:file-type-xml' },
      ],
    },
    {
      id: getId(),
      name: 'Overlay Builder',
      url: 'https://github.com/Mahmud0808/OverlayBuilder',
      repo: 'https://github.com/Mahmud0808/OverlayBuilder',
      img: 'https://i.postimg.cc/DznZSzXZ/overlaybuilder.jpg',
      year: 2021,
      projectSkills: [
        { name: 'GitHub Actions', icon: 'fa-brands:github' },
        { name: 'Shell Script', icon: 'vscode-icons:file-type-shell' },
      ],
    },
    {
      id: getId(),
      name: 'To-Do List',
      url: 'https://github.com/Mahmud0808/ToDoList',
      repo: 'https://github.com/Mahmud0808/ToDoList',
      img: 'https://i.postimg.cc/BqfxBQCm/todolist.png',
      year: 2021,
      projectSkills: [
        { name: 'HTML', icon: 'vscode-icons:file-type-html' },
        { name: 'CSS', icon: 'vscode-icons:file-type-css' },
        { name: 'PHP', icon: 'vscode-icons:file-type-php' },
        { name: 'MySQL', icon: 'tabler:brand-mysql' },
      ],
    },
  ],
};
