import { ProjectsSectionType } from '@/lib/types/sections';
import { getId } from '@/lib/utils/helper';

// https://icon-sets.iconify.design/vscode-icons/

export const projectsSection: ProjectsSectionType = {
  title: 'Other Projects',
  projects: [
    {
      id: getId(),
      name: 'Lammah',
      subtitle: 'Discover, create, and join local events',
      url: 'https://github.com/Mahmud0808/Lammah',
      repo: 'https://github.com/Mahmud0808/Lammah',
      img: 'https://i.postimg.cc/Y0wNqk9P/lammah.png',
      year: 2025,
      projectSkills: [
        { name: 'Flutter', icon: 'vscode-icons:file-type-flutter' },
        { name: 'Dart', icon: 'vscode-icons:file-type-dartlang' },
        { name: 'Rest API', icon: 'vscode-icons:file-type-rest' },
        { name: 'Firebase', icon: 'vscode-icons:file-type-firebase' },
      ],
    },
    {
      id: getId(),
      name: 'Family Arbore',
      subtitle: 'Social Media Platform For Families',
      url: 'https://github.com/Mahmud0808/FamilyArbore',
      repo: 'https://github.com/Mahmud0808/FamilyArbore',
      img: 'https://i.postimg.cc/4nkKgKzY/familyarbore.png',
      year: 2025,
      projectSkills: [
        { name: 'Flutter', icon: 'vscode-icons:file-type-flutter' },
        { name: 'Dart', icon: 'vscode-icons:file-type-dartlang' },
        { name: 'Rest API', icon: 'vscode-icons:file-type-rest' },
        { name: 'WebSocket', icon: 'icon-park:round-socket' },
      ],
    },
    {
      id: getId(),
      name: 'Mind Track',
      subtitle: 'Production-Ready Task Tracker App',
      url: 'https://github.com/Mahmud0808/MindTrack',
      repo: 'https://github.com/Mahmud0808/MindTrack',
      img: 'https://i.postimg.cc/F151FDKs/mindtrack.png',
      year: 2025,
      projectSkills: [
        { name: 'Kotlin', icon: 'vscode-icons:file-type-kotlin' },
        { name: 'MySQL', icon: 'tabler:brand-mysql' },
      ],
    },
    {
      id: getId(),
      name: 'LED Display',
      subtitle: 'Digital Signage Controller System',
      url: 'https://github.com/Mahmud0808/LEDDisplayController',
      repo: 'https://github.com/Mahmud0808/LEDDisplayController',
      img: 'https://i.postimg.cc/s2Sfnpfp/digital-signage.png',
      year: 2025,
      projectSkills: [
        { name: 'Java', icon: 'hugeicons:java' },
        { name: 'Rest API', icon: 'vscode-icons:file-type-rest' },
        { name: 'OkHttp', icon: 'material-symbols:http' },
        { name: 'JavaScript', icon: 'vscode-icons:file-type-js' },
        { name: 'Node.js', icon: 'vscode-icons:file-type-node' },
      ],
    },
    {
      id: getId(),
      name: 'CareerPath+',
      subtitle: 'Career Search and Planning Platform',
      url: 'https://github.com/Mahmud0808/CareerPathPlus',
      repo: 'https://github.com/Mahmud0808/CareerPathPlus',
      img: 'https://i.postimg.cc/cLZ8hbpX/careerpathplus-banner.png',
      year: 2025,
      projectSkills: [
        { name: 'Java', icon: 'hugeicons:java' },
        { name: 'Spring Boot', icon: 'logos:spring-icon' },
        { name: 'Firebase', icon: 'vscode-icons:file-type-firebase' },
        { name: 'Neon Tech', icon: 'logos:neon-icon' },
        { name: 'PostgreSQL', icon: 'logos:postgresql' },
      ],
    },
    {
      id: getId(),
      name: 'Ryda',
      subtitle: 'Ride-Sharing Mobile Application',
      url: 'https://github.com/Mahmud0808/Ryda',
      repo: 'https://github.com/Mahmud0808/Ryda',
      img: 'https://i.postimg.cc/PqwjjvvL/ryda-banner.jpg',
      year: 2025,
      projectSkills: [
        { name: 'React Native', icon: 'vscode-icons:file-type-reactjs' },
        { name: 'Expo', icon: 'vscode-icons:file-type-expo' },
        { name: 'Maps API', icon: 'logos:google-maps' },
        { name: 'Clerk', icon: 'simple-icons:clerk' },
        { name: 'NativeWind', icon: 'vscode-icons:file-type-tailwind' },
        { name: 'Stripe', icon: 'vscode-icons:file-type-silverstripe' },
      ],
    },
    {
      id: getId(),
      name: 'PixelLauncher Enhanced',
      subtitle: 'Android Launcher Customization',
      url: 'https://github.com/Mahmud0808/PixelLauncherEnhanced',
      repo: 'https://github.com/Mahmud0808/PixelLauncherEnhanced',
      img: 'https://i.postimg.cc/SxgRxt4L/PLEnhanced.png',
      year: 2025,
      projectSkills: [
        { name: 'Kotlin', icon: 'vscode-icons:file-type-kotlin' },
        { name: 'XML', icon: 'vscode-icons:file-type-xml' },
        { name: 'Xposed Framework', icon: 'arcticons:xposed' },
      ],
    },
    {
      id: getId(),
      name: 'Truck Orbit',
      subtitle: 'Logistics Tracking Mobile App',
      url: 'https://github.com/Mahmud0808/TruckOrbit',
      repo: 'https://github.com/Mahmud0808/TruckOrbit',
      img: 'https://i.postimg.cc/tRMFT5NM/Truck-Orbit.png',
      year: 2025,
      projectSkills: [
        { name: 'Kotlin', icon: 'vscode-icons:file-type-kotlin' },
        { name: 'Firebase', icon: 'vscode-icons:file-type-firebase' },
        { name: 'Maps API', icon: 'logos:google-maps' },
      ],
    },
    {
      id: getId(),
      name: 'Exam Timer',
      subtitle: 'Timed Exam Management Tool',
      url: 'https://quiktimer.vercel.app',
      repo: 'https://github.com/Mahmud0808/ExamTimer',
      img: 'https://i.postimg.cc/1Xtd7rQS/Exam-Timer.png',
      year: 2024,
      projectSkills: [
        { name: 'Next.js', icon: 'file-icons:nextjs' },
        { name: 'Tailwind CSS', icon: 'vscode-icons:file-type-tailwind' },
      ],
    },
    {
      id: getId(),
      name: 'Breakdown Assistance',
      subtitle: 'Roadside Assistance Mobile App',
      url: 'https://github.com/Mahmud0808/BreakdownAssistance',
      repo: 'https://github.com/Mahmud0808/BreakdownAssistance',
      img: 'https://i.postimg.cc/3Jsq0QGT/Breakdown-Assistance.png',
      year: 2024,
      projectSkills: [
        { name: 'Java', icon: 'hugeicons:java' },
        { name: 'Firebase', icon: 'vscode-icons:file-type-firebase' },
        { name: 'Maps API', icon: 'logos:google-maps' },
      ],
    },
    {
      id: getId(),
      name: 'NexuTalk',
      subtitle: 'Real-Time Chat Application',
      url: 'https://nexutalk.vercel.app/',
      repo: 'https://github.com/Mahmud0808/NexuTalk',
      img: 'https://i.postimg.cc/FhzMbpVC/Screen-Shot-Tool-20240804191942.png',
      year: 2024,
      projectSkills: [
        { name: 'Next.js', icon: 'file-icons:nextjs' },
        { name: 'NextAuth.js', icon: 'noto-v1:shield' },
        { name: 'MongoDB', icon: 'vscode-icons:file-type-mongo' },
        { name: 'Tailwind CSS', icon: 'vscode-icons:file-type-tailwind' },
        { name: 'Prisma', icon: 'simple-icons:prisma' },
        { name: 'Pusher', icon: 'simple-icons:pusher' },
      ],
    },
    {
      id: getId(),
      name: 'MernAuth',
      subtitle: 'Secure MERN Stack Authentication',
      url: 'https://mernauth-mwjp.onrender.com/',
      repo: 'https://github.com/Mahmud0808/MernAuth',
      img: 'https://i.postimg.cc/L9gTVFCs/MernAuth.png',
      year: 2024,
      projectSkills: [
        { name: 'MongoDB', icon: 'vscode-icons:file-type-mongo' },
        { name: 'Express', icon: 'skill-icons:expressjs-light' },
        { name: 'React', icon: 'vscode-icons:file-type-reactjs' },
        { name: 'Node.js', icon: 'vscode-icons:file-type-node' },
        { name: 'Tailwind CSS', icon: 'vscode-icons:file-type-tailwind' },
        { name: 'Firebase', icon: 'vscode-icons:file-type-firebase' },
      ],
    },
    {
      id: getId(),
      name: 'Melodify',
      subtitle: 'Cross-Platform Music Player App',
      url: 'https://github.com/Mahmud0808/Melodify',
      repo: 'https://github.com/Mahmud0808/Melodify',
      img: 'https://i.postimg.cc/WbYQ7f55/Melodify.png',
      year: 2024,
      projectSkills: [
        { name: 'Flutter', icon: 'vscode-icons:file-type-flutter' },
        { name: 'Dart', icon: 'vscode-icons:file-type-dartlang' },
        { name: 'Music Player', icon: 'emojione-v1:music-descend' },
      ],
    },
    {
      id: getId(),
      name: 'ResumeAI',
      subtitle: 'AI-Powered Resume Builder',
      url: 'https://resume-ai-app.vercel.app/',
      repo: 'https://github.com/Mahmud0808/ResumeAI',
      img: 'https://i.postimg.cc/DnJHZ229/Resume-AI.png',
      year: 2024,
      projectSkills: [
        { name: 'Next.js', icon: 'file-icons:nextjs' },
        { name: 'Tailwind CSS', icon: 'vscode-icons:file-type-tailwind' },
        { name: 'MongoDB', icon: 'vscode-icons:file-type-mongo' },
        { name: 'Clerk', icon: 'simple-icons:clerk' },
        { name: 'Gemini API', icon: 'ri:gemini-fill' },
      ],
    },
    {
      id: getId(),
      name: 'Quanta Bank',
      subtitle: 'Secure Bank Account Management',
      url: 'https://github.com/Mahmud0808/QuantaBank',
      repo: 'https://github.com/Mahmud0808/QuantaBank',
      img: 'https://i.postimg.cc/66gtfQJP/quanta-bank.png',
      year: 2024,
      projectSkills: [
        { name: 'Next.js', icon: 'file-icons:nextjs' },
        { name: 'Tailwind CSS', icon: 'vscode-icons:file-type-tailwind' },
        { name: 'Clerk', icon: 'simple-icons:clerk' },
        { name: 'Appwrite', icon: 'logos:appwrite-icon' },
        { name: 'Sentry', icon: 'vscode-icons:file-type-sentry' },
      ],
    },
    {
      id: getId(),
      name: 'Quirklr',
      subtitle: 'Social Networking Web App',
      url: 'https://quirklrapp.vercel.app/',
      repo: 'https://github.com/Mahmud0808/Quirklr',
      img: 'https://i.postimg.cc/hSL5JvrB/quirklr.png',
      year: 2024,
      projectSkills: [
        { name: 'Next.js', icon: 'file-icons:nextjs' },
        { name: 'Tailwind CSS', icon: 'vscode-icons:file-type-tailwind' },
        { name: 'MongoDB', icon: 'vscode-icons:file-type-mongo' },
        { name: 'Clerk', icon: 'simple-icons:clerk' },
      ],
    },
    {
      id: getId(),
      name: 'Nexara Cart',
      subtitle: 'E-Commerce Mobile Application',
      url: 'https://github.com/Mahmud0808/NexaraCart',
      repo: 'https://github.com/Mahmud0808/NexaraCart',
      img: 'https://i.postimg.cc/0ksn4Wjx/Nexara-Cart.png',
      year: 2024,
      projectSkills: [
        { name: 'Flutter', icon: 'vscode-icons:file-type-flutter' },
        { name: 'Dart', icon: 'vscode-icons:file-type-dartlang' },
        { name: 'Node.js', icon: 'vscode-icons:file-type-node' },
      ],
    },
    {
      id: getId(),
      name: 'Lumi Weather',
      subtitle: 'Weather Forecasting Mobile App',
      url: 'https://github.com/Mahmud0808/LumiWeather',
      repo: 'https://github.com/Mahmud0808/LumiWeather',
      img: 'https://i.postimg.cc/B4GHsLBZ/Lumi-Weather.png',
      year: 2024,
      projectSkills: [
        { name: 'Flutter', icon: 'vscode-icons:file-type-flutter' },
        { name: 'Dart', icon: 'vscode-icons:file-type-dartlang' },
      ],
    },
    {
      id: getId(),
      name: 'TG Join Bot',
      subtitle: 'Telegram Group Management Bot',
      url: 'https://github.com/Mahmud0808/TelegramJoinRequestVerifier',
      repo: 'https://github.com/Mahmud0808/TelegramJoinRequestVerifier',
      img: 'https://i.postimg.cc/hgntt96Y/TGJoin-Bot.png',
      year: 2024,
      projectSkills: [
        { name: 'Kotlin', icon: 'vscode-icons:file-type-kotlin' },
        { name: 'Telegram', icon: 'logos:telegram' },
        { name: 'Bot', icon: 'bxs:bot' },
      ],
    },
    {
      id: getId(),
      name: 'UniRide',
      subtitle: 'University Transport Management App',
      url: 'https://github.com/Mahmud0808/UniRide',
      repo: 'https://github.com/Mahmud0808/UniRide',
      img: 'https://i.postimg.cc/4GFBY02y/uniride.png',
      year: 2024,
      projectSkills: [
        { name: 'Kotlin', icon: 'vscode-icons:file-type-kotlin' },
        { name: 'Firebase', icon: 'vscode-icons:file-type-firebase' },
        { name: 'Maps API', icon: 'logos:google-maps' },
        { name: 'Gemini API', icon: 'ri:gemini-fill' },
      ],
    },
    {
      id: getId(),
      name: 'Conversa',
      subtitle: 'AI-Powered Chat Application',
      url: 'https://github.com/Mahmud0808/Conversa',
      repo: 'https://github.com/Mahmud0808/Conversa',
      img: 'https://i.postimg.cc/VsgKtc87/conversa.png',
      year: 2024,
      projectSkills: [
        { name: 'Kotlin', icon: 'vscode-icons:file-type-kotlin' },
        { name: 'Gemini API', icon: 'ri:gemini-fill' },
      ],
    },
    {
      id: getId(),
      name: 'Rushly',
      subtitle: 'E-Commerce Mobile App',
      url: 'https://github.com/Mahmud0808/Rushly',
      repo: 'https://github.com/Mahmud0808/Rushly',
      img: 'https://i.postimg.cc/yN3mpw2z/rushly.webp',
      year: 2024,
      projectSkills: [
        { name: 'Kotlin', icon: 'vscode-icons:file-type-kotlin' },
        { name: 'Firebase', icon: 'vscode-icons:file-type-firebase' },
      ],
    },
    {
      id: getId(),
      name: 'ThunderDex',
      subtitle: 'War Thunder Information Hub',
      url: 'https://play.google.com/store/apps/details?id=io.hifii.wiki',
      repo: 'https://github.com/Mahmud0808/WarThunderWiki',
      img: 'https://i.postimg.cc/VvV21ysW-/opengraph-wt.jpg',
      year: 2024,
      projectSkills: [
        { name: 'Java', icon: 'hugeicons:java' },
        { name: 'HTML', icon: 'vscode-icons:file-type-html' },
        { name: 'War Thunder', icon: 'healthicons:war' },
      ],
    },
    {
      id: getId(),
      name: 'RemiLab',
      subtitle: 'System Preference Management Tool',
      url: 'https://github.com/Mahmud0808/RemiLab',
      repo: 'https://github.com/Mahmud0808/RemiLab',
      img: 'https://i.postimg.cc/Fs9sP3wr/remilab.png',
      year: 2024,
      projectSkills: [
        { name: 'Java', icon: 'hugeicons:java' },
        { name: 'Shell Script', icon: 'vscode-icons:file-type-shell' },
        {
          name: 'Preference Manager',
          icon: 'material-symbols:room-preferences-rounded',
        },
      ],
    },
    {
      id: getId(),
      name: 'Sonix Spectrum',
      subtitle: 'Kernel Optimization Tool',
      url: 'https://github.com/Mahmud0808/Sonix-Spectrum',
      repo: 'https://github.com/Mahmud0808/Sonix-Spectrum',
      img: 'https://i.postimg.cc/cCs23Vcf/sonixspectrum.jpg',
      year: 2024,
      projectSkills: [
        { name: 'Java', icon: 'hugeicons:java' },
        { name: 'Shell Script', icon: 'vscode-icons:file-type-shell' },
        { name: 'Kernel Manager', icon: 'ph:cpu-bold' },
      ],
    },
    {
      id: getId(),
      name: 'SheGuard',
      subtitle: 'Women’s Safety Mobile App',
      url: 'https://github.com/Mahmud0808/SheGuard',
      repo: 'https://github.com/Mahmud0808/SheGuard',
      img: 'https://i.postimg.cc/rVfKvhCd/sheguard.png',
      year: 2023,
      projectSkills: [
        { name: 'Java', icon: 'hugeicons:java' },
        { name: 'Firebase', icon: 'vscode-icons:file-type-firebase' },
      ],
    },
    {
      id: getId(),
      name: 'MusicPlayer',
      subtitle: 'Web-Based Music Player',
      url: 'https://mahmud0808.github.io/MusicPlayer',
      repo: 'https://github.com/Mahmud080Objectives: Create a web-based music player using HTML, CSS, and JavaScript. The project focuses on delivering a seamless audio playback experience with a clean and intuitive interface.',
      img: 'https://i.postimg.cc/D2TNDhgz/musicplayer.png',
      year: 2023,
      projectSkills: [
        { name: 'HTML', icon: 'vscode-icons:file-type-html' },
        { name: 'CSS', icon: 'vscode-icons:file-type-css' },
        { name: 'JavaScript', icon: 'vscode-icons:file-type-js' },
        { name: 'Music Player', icon: 'emojione-v1:music-descend' },
      ],
    },
    {
      id: getId(),
      name: 'QuizMania',
      subtitle: 'Interactive Quiz Web App',
      url: 'https://mahmud0808.github.io/QuizMania',
      repo: 'https://github.com/Mahmud0808/QuizMania',
      img: 'https://i.postimg.cc/R404s70Y/quizmania.png',
      year: 2023,
      projectSkills: [
        { name: 'HTML', icon: 'vscode-icons:file-type-html' },
        { name: 'CSS', icon: 'vscode-icons:file-type-css' },
        { name: 'JavaScript', icon: 'vscode-icons:file-type-js' },
      ],
    },
    {
      id: getId(),
      name: 'FRAS',
      subtitle: 'Facial Recognition Attendance System',
      url: 'https://github.com/Mahmud0808/FRAS',
      repo: 'https://github.com/Mahmud0808/FRAS',
      img: 'https://i.postimg.cc/59phw2QG/fras.jpg',
      year: 2022,
      projectSkills: [
        { name: 'Python', icon: 'vscode-icons:file-type-python' },
        { name: 'Flask', icon: 'simple-icons:flask' },
        { name: 'Image Processing', icon: 'ic:baseline-face' },
      ],
    },
    {
      id: getId(),
      name: 'Gadgets',
      subtitle: 'Gadget Showcase Website',
      url: 'https://mahmud0808.github.io/Gadgets',
      repo: 'https://github.com/Mahmud0808/Gadgets',
      img: 'https://i.postimg.cc/MqWPSt2W/gadgets.png',
      year: 2022,
      projectSkills: [
        { name: 'HTML', icon: 'vscode-icons:file-type-html' },
        { name: 'CSS', icon: 'vscode-icons:file-type-css' },
      ],
    },
    {
      id: getId(),
      name: 'Another Theme',
      subtitle: 'Android Theme Customization',
      url: 'https://www.pling.com/p/1732643',
      repo: 'https://github.com/Mahmud0808/AnotherTheme',
      img: 'https://i.postimg.cc/FN3T3qyg/heroimage.png',
      year: 2022,
      projectSkills: [
        { name: 'Kotlin', icon: 'vscode-icons:file-type-kotlin' },
        { name: 'XML', icon: 'vscode-icons:file-type-xml' },
        { name: 'Substratum', icon: 'arcticons:substratum' },
      ],
    },
    {
      id: getId(),
      name: 'Pink Bean (Monet)',
      subtitle: 'Monet-Inspired Notification Icon Theme',
      url: 'https://www.pling.com/p/1732643',
      repo: 'https://github.com/Mahmud0808/PinkBeanMonet',
      img: 'https://i.postimg.cc/xngVLcyP/heroimage.png',
      year: 2022,
      projectSkills: [
        { name: 'Kotlin', icon: 'vscode-icons:file-type-kotlin' },
        { name: 'XML', icon: 'vscode-icons:file-type-xml' },
        { name: 'Substratum', icon: 'arcticons:substratum' },
      ],
    },
    {
      id: getId(),
      name: 'Pink Bean',
      subtitle: 'Notification Icon Theme',
      url: 'https://www.pling.com/p/1732643',
      repo: 'https://github.com/Mahmud0808/PinkBean',
      img: 'https://i.postimg.cc/v8McjcKm/heroimage.png',
      year: 2022,
      projectSkills: [
        { name: 'Kotlin', icon: 'vscode-icons:file-type-kotlin' },
        { name: 'XML', icon: 'vscode-icons:file-type-xml' },
        { name: 'Substratum', icon: 'arcticons:substratum' },
      ],
    },
    {
      id: getId(),
      name: 'Overlay Builder',
      subtitle: 'Automated Theme Overlay Tool',
      url: 'https://github.com/Mahmud0808/OverlayBuilder',
      repo: 'https://github.com/Mahmud0808/OverlayBuilder',
      img: 'https://i.postimg.cc/DznZSzXZ/overlaybuilder.jpg',
      year: 2021,
      projectSkills: [
        { name: 'GitHub Actions', icon: 'fa-brands:github' },
        { name: 'Shell Script', icon: 'vscode-icons:file-type-shell' },
      ],
    },
    {
      id: getId(),
      name: 'To-Do List',
      subtitle: 'Task Management Web App',
      url: 'https://github.com/Mahmud0808/ToDoList',
      repo: 'https://github.com/Mahmud0808/ToDoList',
      img: 'https://i.postimg.cc/BqfxBQCm/todolist.png',
      year: 2021,
      projectSkills: [
        { name: 'HTML', icon: 'vscode-icons:file-type-html' },
        { name: 'CSS', icon: 'vscode-icons:file-type-css' },
        { name: 'PHP', icon: 'vscode-icons:file-type-php' },
        { name: 'MySQL', icon: 'tabler:brand-mysql' },
      ],
    },
  ],
};
