import { ProjectsSectionType } from '@/lib/types/sections';
import { getId } from '@/lib/utils/helper';

// https://icon-sets.iconify.design/vscode-icons/

export const projectsSection: ProjectsSectionType = {
  title: 'Other Projects',
  projects: [
    {
      id: getId(),
      name: 'Appwise',
      subtitle: 'Track Unused Apps and Subscriptions',
      url: 'https://play.google.com/store/apps/details?id=com.drdisagree.appwise',
      repo: 'https://play.google.com/store/apps/details?id=com.drdisagree.appwise',
      img: '/images/projects/appwise.webp',
      year: 2026,
      projectSkills: [
        { name: 'Kotlin', icon: 'vscode-icons:file-type-kotlin' },
        { name: 'Jetpack Compose', icon: 'devicon:jetpackcompose' },
        { name: 'Google Playstore', icon: 'mage:playstore' },
      ],
    },
    {
      id: getId(),
      name: 'Lammah',
      subtitle: 'Discover, Create, and Join Local Events',
      url: 'https://github.com/Mahmud0808/Lammah',
      repo: 'https://github.com/Mahmud0808/Lammah',
      img: '/images/projects/lammah.webp',
      year: 2025,
      projectSkills: [
        { name: 'Flutter', icon: 'vscode-icons:file-type-flutter' },
        { name: 'Dart', icon: 'vscode-icons:file-type-dartlang' },
        { name: 'Rest API', icon: 'vscode-icons:file-type-rest' },
        { name: 'Firebase', icon: 'vscode-icons:file-type-firebase' },
      ],
    },
    {
      id: getId(),
      name: 'Family Arbore',
      subtitle: 'Social Media Platform For Families',
      url: 'https://github.com/Mahmud0808/FamilyArbore',
      repo: 'https://github.com/Mahmud0808/FamilyArbore',
      img: '/images/projects/family-arbore.webp',
      year: 2025,
      projectSkills: [
        { name: 'Flutter', icon: 'vscode-icons:file-type-flutter' },
        { name: 'Dart', icon: 'vscode-icons:file-type-dartlang' },
        { name: 'Rest API', icon: 'vscode-icons:file-type-rest' },
        { name: 'WebSocket', icon: 'icon-park:round-socket' },
      ],
    },
    {
      id: getId(),
      name: 'Mind Track',
      subtitle: 'Production-Ready Task Tracker App',
      url: 'https://github.com/Mahmud0808/MindTrack',
      repo: 'https://github.com/Mahmud0808/MindTrack',
      img: '/images/projects/mind-track.webp',
      year: 2025,
      projectSkills: [
        { name: 'Kotlin', icon: 'vscode-icons:file-type-kotlin' },
        { name: 'MySQL', icon: 'tabler:brand-mysql' },
      ],
    },
    {
      id: getId(),
      name: 'LED Display',
      subtitle: 'Digital Signage Controller System',
      url: 'https://github.com/Mahmud0808/LEDDisplayController',
      repo: 'https://github.com/Mahmud0808/LEDDisplayController',
      img: '/images/projects/digital-signage.webp',
      year: 2025,
      projectSkills: [
        { name: 'Java', icon: 'hugeicons:java' },
        { name: 'Rest API', icon: 'vscode-icons:file-type-rest' },
        { name: 'OkHttp', icon: 'material-symbols:http' },
        { name: 'JavaScript', icon: 'vscode-icons:file-type-js' },
        { name: 'Node.js', icon: 'vscode-icons:file-type-node' },
      ],
    },
    {
      id: getId(),
      name: 'CareerPath+',
      subtitle: 'Career Search and Planning Platform',
      url: 'https://github.com/Mahmud0808/CareerPathPlus',
      repo: 'https://github.com/Mahmud0808/CareerPathPlus',
      img: '/images/projects/career-path-plus.webp',
      year: 2025,
      projectSkills: [
        { name: 'Java', icon: 'hugeicons:java' },
        { name: 'Spring Boot', icon: 'logos:spring-icon' },
        { name: 'Firebase', icon: 'vscode-icons:file-type-firebase' },
        { name: 'Neon Tech', icon: 'logos:neon-icon' },
        { name: 'PostgreSQL', icon: 'logos:postgresql' },
      ],
    },
    {
      id: getId(),
      name: 'Ryda',
      subtitle: 'Ride-Sharing Mobile Application',
      url: 'https://github.com/Mahmud0808/Ryda',
      repo: 'https://github.com/Mahmud0808/Ryda',
      img: '/images/projects/ryda.webp',
      year: 2025,
      projectSkills: [
        { name: 'React Native', icon: 'vscode-icons:file-type-reactjs' },
        { name: 'Expo', icon: 'vscode-icons:file-type-expo' },
        { name: 'Maps API', icon: 'logos:google-maps' },
        { name: 'Clerk', icon: 'simple-icons:clerk' },
        { name: 'NativeWind', icon: 'vscode-icons:file-type-tailwind' },
        { name: 'Stripe', icon: 'vscode-icons:file-type-silverstripe' },
      ],
    },
    {
      id: getId(),
      name: 'PixelLauncher Enhanced',
      subtitle: 'Android Launcher Customization',
      url: 'https://github.com/Mahmud0808/PixelLauncherEnhanced',
      repo: 'https://github.com/Mahmud0808/PixelLauncherEnhanced',
      img: '/images/projects/plenhanced.webp',
      year: 2025,
      projectSkills: [
        { name: 'Kotlin', icon: 'vscode-icons:file-type-kotlin' },
        { name: 'XML', icon: 'vscode-icons:file-type-xml' },
        { name: 'Xposed Framework', icon: 'arcticons:xposed' },
      ],
    },
    {
      id: getId(),
      name: 'Truck Orbit',
      subtitle: 'Logistics Tracking Mobile App',
      url: 'https://github.com/Mahmud0808/TruckOrbit',
      repo: 'https://github.com/Mahmud0808/TruckOrbit',
      img: '/images/projects/truck-orbit.webp',
      year: 2025,
      projectSkills: [
        { name: 'Kotlin', icon: 'vscode-icons:file-type-kotlin' },
        { name: 'Firebase', icon: 'vscode-icons:file-type-firebase' },
        { name: 'Maps API', icon: 'logos:google-maps' },
      ],
    },
    {
      id: getId(),
      name: 'Exam Timer',
      subtitle: 'Timed Exam Management Tool',
      url: 'https://quiktimer.vercel.app',
      repo: 'https://github.com/Mahmud0808/ExamTimer',
      img: '/images/projects/exam-timer.webp',
      year: 2024,
      projectSkills: [
        { name: 'Next.js', icon: 'file-icons:nextjs' },
        { name: 'Tailwind CSS', icon: 'vscode-icons:file-type-tailwind' },
      ],
    },
    {
      id: getId(),
      name: 'Breakdown Assistance',
      subtitle: 'Roadside Assistance Mobile App',
      url: 'https://github.com/Mahmud0808/BreakdownAssistance',
      repo: 'https://github.com/Mahmud0808/BreakdownAssistance',
      img: '/images/projects/breakdown-assistance.webp',
      year: 2024,
      projectSkills: [
        { name: 'Java', icon: 'hugeicons:java' },
        { name: 'Firebase', icon: 'vscode-icons:file-type-firebase' },
        { name: 'Maps API', icon: 'logos:google-maps' },
      ],
    },
    {
      id: getId(),
      name: 'NexuTalk',
      subtitle: 'Real-Time Chat Application',
      url: 'https://nexutalk.vercel.app/',
      repo: 'https://github.com/Mahmud0808/NexuTalk',
      img: '/images/projects/nexutalk.webp',
      year: 2024,
      projectSkills: [
        { name: 'Next.js', icon: 'file-icons:nextjs' },
        { name: 'NextAuth.js', icon: 'noto-v1:shield' },
        { name: 'MongoDB', icon: 'vscode-icons:file-type-mongo' },
        { name: 'Tailwind CSS', icon: 'vscode-icons:file-type-tailwind' },
        { name: 'Prisma', icon: 'simple-icons:prisma' },
        { name: 'Pusher', icon: 'simple-icons:pusher' },
      ],
    },
    {
      id: getId(),
      name: 'MernAuth',
      subtitle: 'Secure MERN Stack Authentication',
      url: 'https://mernauth-mwjp.onrender.com/',
      repo: 'https://github.com/Mahmud0808/MernAuth',
      img: '/images/projects/mern-auth.webp',
      year: 2024,
      projectSkills: [
        { name: 'MongoDB', icon: 'vscode-icons:file-type-mongo' },
        { name: 'Express', icon: 'skill-icons:expressjs-light' },
        { name: 'React', icon: 'vscode-icons:file-type-reactjs' },
        { name: 'Node.js', icon: 'vscode-icons:file-type-node' },
        { name: 'Tailwind CSS', icon: 'vscode-icons:file-type-tailwind' },
        { name: 'Firebase', icon: 'vscode-icons:file-type-firebase' },
      ],
    },
    {
      id: getId(),
      name: 'Melodify',
      subtitle: 'Cross-Platform Music Player App',
      url: 'https://github.com/Mahmud0808/Melodify',
      repo: 'https://github.com/Mahmud0808/Melodify',
      img: '/images/projects/melodify.webp',
      year: 2024,
      projectSkills: [
        { name: 'Flutter', icon: 'vscode-icons:file-type-flutter' },
        { name: 'Dart', icon: 'vscode-icons:file-type-dartlang' },
        { name: 'Music Player', icon: 'emojione-v1:music-descend' },
      ],
    },
    {
      id: getId(),
      name: 'ResumeAI',
      subtitle: 'AI-Powered Resume Builder',
      url: 'https://resume-ai-app.vercel.app/',
      repo: 'https://github.com/Mahmud0808/ResumeAI',
      img: '/images/projects/resume-ai.webp',
      year: 2024,
      projectSkills: [
        { name: 'Next.js', icon: 'file-icons:nextjs' },
        { name: 'Tailwind CSS', icon: 'vscode-icons:file-type-tailwind' },
        { name: 'MongoDB', icon: 'vscode-icons:file-type-mongo' },
        { name: 'Clerk', icon: 'simple-icons:clerk' },
        { name: 'Gemini API', icon: 'ri:gemini-fill' },
      ],
    },
    {
      id: getId(),
      name: 'Quanta Bank',
      subtitle: 'Secure Bank Account Management',
      url: 'https://github.com/Mahmud0808/QuantaBank',
      repo: 'https://github.com/Mahmud0808/QuantaBank',
      img: '/images/projects/quanta-bank.webp',
      year: 2024,
      projectSkills: [
        { name: 'Next.js', icon: 'file-icons:nextjs' },
        { name: 'Tailwind CSS', icon: 'vscode-icons:file-type-tailwind' },
        { name: 'Clerk', icon: 'simple-icons:clerk' },
        { name: 'Appwrite', icon: 'logos:appwrite-icon' },
        { name: 'Sentry', icon: 'vscode-icons:file-type-sentry' },
      ],
    },
    {
      id: getId(),
      name: 'Quirklr',
      subtitle: 'Social Networking Web App',
      url: 'https://quirklrapp.vercel.app/',
      repo: 'https://github.com/Mahmud0808/Quirklr',
      img: '/images/projects/quirklr.webp',
      year: 2024,
      projectSkills: [
        { name: 'Next.js', icon: 'file-icons:nextjs' },
        { name: 'Tailwind CSS', icon: 'vscode-icons:file-type-tailwind' },
        { name: 'MongoDB', icon: 'vscode-icons:file-type-mongo' },
        { name: 'Clerk', icon: 'simple-icons:clerk' },
      ],
    },
    {
      id: getId(),
      name: 'Nexara Cart',
      subtitle: 'E-Commerce Mobile Application',
      url: 'https://github.com/Mahmud0808/NexaraCart',
      repo: 'https://github.com/Mahmud0808/NexaraCart',
      img: '/images/projects/nexara-cart.webp',
      year: 2024,
      projectSkills: [
        { name: 'Flutter', icon: 'vscode-icons:file-type-flutter' },
        { name: 'Dart', icon: 'vscode-icons:file-type-dartlang' },
        { name: 'Node.js', icon: 'vscode-icons:file-type-node' },
      ],
    },
    {
      id: getId(),
      name: 'Lumi Weather',
      subtitle: 'Weather Forecasting Mobile App',
      url: 'https://github.com/Mahmud0808/LumiWeather',
      repo: 'https://github.com/Mahmud0808/LumiWeather',
      img: '/images/projects/lumi-weather.webp',
      year: 2024,
      projectSkills: [
        { name: 'Flutter', icon: 'vscode-icons:file-type-flutter' },
        { name: 'Dart', icon: 'vscode-icons:file-type-dartlang' },
      ],
    },
    {
      id: getId(),
      name: 'TG Join Bot',
      subtitle: 'Telegram Group Management Bot',
      url: 'https://github.com/Mahmud0808/TelegramJoinRequestVerifier',
      repo: 'https://github.com/Mahmud0808/TelegramJoinRequestVerifier',
      img: '/images/projects/tg-join-bot.webp',
      year: 2024,
      projectSkills: [
        { name: 'Kotlin', icon: 'vscode-icons:file-type-kotlin' },
        { name: 'Telegram', icon: 'logos:telegram' },
        { name: 'Bot', icon: 'bxs:bot' },
      ],
    },
    {
      id: getId(),
      name: 'UniRide',
      subtitle: 'University Transport Management App',
      url: 'https://github.com/Mahmud0808/UniRide',
      repo: 'https://github.com/Mahmud0808/UniRide',
      img: '/images/projects/uniride.webp',
      year: 2024,
      projectSkills: [
        { name: 'Kotlin', icon: 'vscode-icons:file-type-kotlin' },
        { name: 'Firebase', icon: 'vscode-icons:file-type-firebase' },
        { name: 'Maps API', icon: 'logos:google-maps' },
        { name: 'Gemini API', icon: 'ri:gemini-fill' },
      ],
    },
    {
      id: getId(),
      name: 'Conversa',
      subtitle: 'AI-Powered Chat Application',
      url: 'https://github.com/Mahmud0808/Conversa',
      repo: 'https://github.com/Mahmud0808/Conversa',
      img: '/images/projects/conversa.webp',
      year: 2024,
      projectSkills: [
        { name: 'Kotlin', icon: 'vscode-icons:file-type-kotlin' },
        { name: 'Gemini API', icon: 'ri:gemini-fill' },
      ],
    },
    {
      id: getId(),
      name: 'Rushly',
      subtitle: 'E-Commerce Mobile App',
      url: 'https://github.com/Mahmud0808/Rushly',
      repo: 'https://github.com/Mahmud0808/Rushly',
      img: '/images/projects/rushly.webp',
      year: 2024,
      projectSkills: [
        { name: 'Kotlin', icon: 'vscode-icons:file-type-kotlin' },
        { name: 'Firebase', icon: 'vscode-icons:file-type-firebase' },
      ],
    },
    {
      id: getId(),
      name: 'ThunderDex',
      subtitle: 'War Thunder Information Hub',
      url: 'https://play.google.com/store/apps/details?id=io.hifii.wiki',
      repo: 'https://github.com/Mahmud0808/WarThunderWiki',
      img: '/images/projects/war-thunder-wiki.webp',
      year: 2024,
      projectSkills: [
        { name: 'Java', icon: 'hugeicons:java' },
        { name: 'HTML', icon: 'vscode-icons:file-type-html' },
        { name: 'War Thunder', icon: 'healthicons:war' },
      ],
    },
    {
      id: getId(),
      name: 'RemiLab',
      subtitle: 'System Preference Management Tool',
      url: 'https://github.com/Mahmud0808/RemiLab',
      repo: 'https://github.com/Mahmud0808/RemiLab',
      img: '/images/projects/remilab.webp',
      year: 2024,
      projectSkills: [
        { name: 'Java', icon: 'hugeicons:java' },
        { name: 'Shell Script', icon: 'vscode-icons:file-type-shell' },
        {
          name: 'Preference Manager',
          icon: 'material-symbols:room-preferences-rounded',
        },
      ],
    },
    {
      id: getId(),
      name: 'Sonix Spectrum',
      subtitle: 'Kernel Optimization Tool',
      url: 'https://github.com/Mahmud0808/Sonix-Spectrum',
      repo: 'https://github.com/Mahmud0808/Sonix-Spectrum',
      img: '/images/projects/sonix-spectrum.webp',
      year: 2024,
      projectSkills: [
        { name: 'Java', icon: 'hugeicons:java' },
        { name: 'Shell Script', icon: 'vscode-icons:file-type-shell' },
        { name: 'Kernel Manager', icon: 'ph:cpu-bold' },
      ],
    },
    {
      id: getId(),
      name: 'SheGuard',
      subtitle: 'Women’s Safety Mobile App',
      url: 'https://github.com/Mahmud0808/SheGuard',
      repo: 'https://github.com/Mahmud0808/SheGuard',
      img: '/images/projects/sheguard.webp',
      year: 2023,
      projectSkills: [
        { name: 'Java', icon: 'hugeicons:java' },
        { name: 'Firebase', icon: 'vscode-icons:file-type-firebase' },
      ],
    },
    {
      id: getId(),
      name: 'MusicPlayer',
      subtitle: 'Web-Based Music Player',
      url: 'https://mahmud0808.github.io/MusicPlayer',
      repo: 'https://github.com/Mahmud080Objectives: Create a web-based music player using HTML, CSS, and JavaScript. The project focuses on delivering a seamless audio playback experience with a clean and intuitive interface.',
      img: '/images/projects/music-player.webp',
      year: 2023,
      projectSkills: [
        { name: 'HTML', icon: 'vscode-icons:file-type-html' },
        { name: 'CSS', icon: 'vscode-icons:file-type-css' },
        { name: 'JavaScript', icon: 'vscode-icons:file-type-js' },
        { name: 'Music Player', icon: 'emojione-v1:music-descend' },
      ],
    },
    {
      id: getId(),
      name: 'QuizMania',
      subtitle: 'Interactive Quiz Web App',
      url: 'https://mahmud0808.github.io/QuizMania',
      repo: 'https://github.com/Mahmud0808/QuizMania',
      img: '/images/projects/quiz-mania.webp',
      year: 2023,
      projectSkills: [
        { name: 'HTML', icon: 'vscode-icons:file-type-html' },
        { name: 'CSS', icon: 'vscode-icons:file-type-css' },
        { name: 'JavaScript', icon: 'vscode-icons:file-type-js' },
      ],
    },
    {
      id: getId(),
      name: 'FRAS',
      subtitle: 'Facial Recognition Attendance System',
      url: 'https://github.com/Mahmud0808/FRAS',
      repo: 'https://github.com/Mahmud0808/FRAS',
      img: '/images/projects/fras.webp',
      year: 2022,
      projectSkills: [
        { name: 'Python', icon: 'vscode-icons:file-type-python' },
        { name: 'Flask', icon: 'simple-icons:flask' },
        { name: 'Image Processing', icon: 'ic:baseline-face' },
      ],
    },
    {
      id: getId(),
      name: 'Gadgets',
      subtitle: 'Gadget Showcase Website',
      url: 'https://mahmud0808.github.io/Gadgets',
      repo: 'https://github.com/Mahmud0808/Gadgets',
      img: '/images/projects/gadgets.webp',
      year: 2022,
      projectSkills: [
        { name: 'HTML', icon: 'vscode-icons:file-type-html' },
        { name: 'CSS', icon: 'vscode-icons:file-type-css' },
      ],
    },
    {
      id: getId(),
      name: 'Another Theme',
      subtitle: 'Android Theme Customization',
      url: 'https://www.pling.com/p/1732643',
      repo: 'https://github.com/Mahmud0808/AnotherTheme',
      img: '/images/projects/another-theme.webp',
      year: 2022,
      projectSkills: [
        { name: 'Kotlin', icon: 'vscode-icons:file-type-kotlin' },
        { name: 'XML', icon: 'vscode-icons:file-type-xml' },
        { name: 'Substratum', icon: 'arcticons:substratum' },
      ],
    },
    {
      id: getId(),
      name: 'Pink Bean (Monet)',
      subtitle: 'Monet-Inspired Notification Icon Theme',
      url: 'https://www.pling.com/p/1732643',
      repo: 'https://github.com/Mahmud0808/PinkBeanMonet',
      img: '/images/projects/pink-bean-monet.webp',
      year: 2022,
      projectSkills: [
        { name: 'Kotlin', icon: 'vscode-icons:file-type-kotlin' },
        { name: 'XML', icon: 'vscode-icons:file-type-xml' },
        { name: 'Substratum', icon: 'arcticons:substratum' },
      ],
    },
    {
      id: getId(),
      name: 'Pink Bean',
      subtitle: 'Notification Icon Theme',
      url: 'https://www.pling.com/p/1732643',
      repo: 'https://github.com/Mahmud0808/PinkBean',
      img: '/images/projects/pink-bean.webp',
      year: 2022,
      projectSkills: [
        { name: 'Kotlin', icon: 'vscode-icons:file-type-kotlin' },
        { name: 'XML', icon: 'vscode-icons:file-type-xml' },
        { name: 'Substratum', icon: 'arcticons:substratum' },
      ],
    },
    {
      id: getId(),
      name: 'Overlay Builder',
      subtitle: 'Automated Theme Overlay Tool',
      url: 'https://github.com/Mahmud0808/OverlayBuilder',
      repo: 'https://github.com/Mahmud0808/OverlayBuilder',
      img: '/images/projects/overlay-builder.webp',
      year: 2021,
      projectSkills: [
        { name: 'GitHub Actions', icon: 'fa-brands:github' },
        { name: 'Shell Script', icon: 'vscode-icons:file-type-shell' },
      ],
    },
    {
      id: getId(),
      name: 'To-Do List',
      subtitle: 'Task Management Web App',
      url: 'https://github.com/Mahmud0808/ToDoList',
      repo: 'https://github.com/Mahmud0808/ToDoList',
      img: '/images/projects/todo-list.webp',
      year: 2021,
      projectSkills: [
        { name: 'HTML', icon: 'vscode-icons:file-type-html' },
        { name: 'CSS', icon: 'vscode-icons:file-type-css' },
        { name: 'PHP', icon: 'vscode-icons:file-type-php' },
        { name: 'MySQL', icon: 'tabler:brand-mysql' },
      ],
    },
  ],
};
