name: GitHub Pages deploy

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v7.0.1

      - name: Use Node.js 24.x
        uses: actions/setup-node@v7.0.0
        with:
          node-version: "24.x"
          cache: yarn

      - name: Installing my packages
        run: yarn install --frozen-lockfile

      - name: Extract repository name
        run: |
          OWNER=$(echo $GITHUB_REPOSITORY | cut -d '/' -f 1)
          REPO=$(echo $GITHUB_REPOSITORY | cut -d '/' -f 2)
          if [ "$REPO" != "${OWNER}.github.io" ]; then
            echo "BASE_PATH=/$REPO" >> $GITHUB_ENV
          fi

      - name: Build my App
        run: yarn build && touch ./out/.nojekyll

      - name: Check quality with Lighthouse
        run: npx --yes @lhci/cli@0.15.1 autorun

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.9.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: public
          folder: out